<?php
return [
    'app-name' => 'Cake<b>LTE</b>',
    'app-logo' => 'CakeLte.cake.icon.svg',
    'small-text' => false,
    'dark-mode' => false,
    'layout-boxed' => false,
    'header.fixed' => false,
    'header.border' => true,
    'header.style' => \CakeLte\View\Styles\Header::STYLE_WHITE,
    'header.dropdown-legacy' => false,
    'sidebar.fixed' => true,
    'sidebar.collapsed' => false,
    'sidebar.mini' => true,
    'sidebar.mini-md' => false,
    'sidebar.mini-xs' => false,
    'sidebar.style' => \CakeLte\View\Styles\Sidebar::STYLE_DARK_PRIMARY,
    'sidebar.flat-style' => false,
    'sidebar.legacy-style' => false,
    'sidebar.compact' => false,
    'sidebar.child-indent' => false,
    'sidebar.child-hide-collapse' => false,
    'sidebar.disabled-auto-expand' => false,
    'footer.fixed' => false,
  ];